#!/bin/sh

if [ $# -le 0 ]; then
    echo "Wrong usage. Example: $0 <dev>"
    exit 1
fi

DEV="$1"

echo "Preparing..."
set -e
sudo bluetoothctl power on
sudo bluetoothctl pairable on
sudo bluetoothctl agent on
set +e
echo ""

echo "Scanning on..."
sudo bluetoothctl default-agent
sudo bluetoothctl --timeout 10 -- scan on
echo ""

echo "Pairing..."
sudo bluetoothctl -- pair "$DEV"
echo ""

echo "Connecting..."
sudo bluetoothctl -- trust "$DEV"
sudo rfcomm release 0 &>/dev/null
sudo rfcomm bind 0 E4:C8:01:84:E3:98
echo ""

echo "Device:"
ls -l /dev/rfcomm0 && echo "Ready to use!"
echo ""
